### ISSUE TITLE
  Unable to create resnet-18

### ISSUE THREAD

**Issue by hbonnavaud** [2016choang/sfl#3]
Unable to create resnet-18

Hi,

In the notebook sfl/playground/vizdoom.ipynb (branch eval) I am trying to build resnet and import weights from SPTM.
However, it looks like there is an issue with your resnet file. Apparently, a stride of 0 is computed when the resnet is build.

```
Traceback (most recent call last):
  File "/home/disc/h.bonnavaud/these/implems/sptm/load_models.py", line 4, in <module>
    sptm_model = resnet.ResnetBuilder.build_siamese_resnet_18((6, 120, 160), 2)
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 351, in build_siamese_resnet_18
    branch = ResnetBuilder.build_resnet_18(branch_input_shape, NUM_EMBEDDING, False)
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 309, in build_resnet_18
    return ResnetBuilder.build(input_shape, num_outputs, basic_block, [2, 2, 2, 2], is_classification)
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 287, in build
    block = _residual_block(block_fn, filters=filters, repetitions=r, is_first_layer=(i == 0))(block)
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 109, in f
    input = block_function(filters=filters, init_strides=init_strides,
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 134, in f
    return _shortcut(input, residual)
  File "/home/disc/h.bonnavaud/these/implems/sptm/sfl/rlpyt/models/resnet.py", line 91, in _shortcut
    shortcut = Conv2D(filters=residual_shape[CHANNEL_AXIS],
  File "/home/disc/h.bonnavaud/these/implems/sptm/venv/lib/python3.8/site-packages/keras/src/dtensor/utils.py", line 96, in _wrap_function
    init_method(layer_instance, *args, **kwargs)
  File "/home/disc/h.bonnavaud/these/implems/sptm/venv/lib/python3.8/site-packages/keras/src/layers/convolutional/conv2d.py", line 179, in __init__
    super().__init__(
  File "/home/disc/h.bonnavaud/these/implems/sptm/venv/lib/python3.8/site-packages/keras/src/layers/convolutional/base_conv.py", line 159, in __init__
    self._validate_init()
  File "/home/disc/h.bonnavaud/these/implems/sptm/venv/lib/python3.8/site-packages/keras/src/layers/convolutional/base_conv.py", line 182, in _validate_init
    raise ValueError(
ValueError: The argument `strides` cannot contains 0(s). Received: (2, 0)
```

First of all, can you tel me which version of tensorflow / keras you are using ? Because I had to replace some function names to make it match with the latest version, which could be a source of issue.

Apparently, run these two lines of code is enough to reproduce the issue :
```
import rlpyt.models.resnet as resnet
sptm_model = resnet.ResnetBuilder.build_siamese_resnet_18((6, 120, 160), 2)
```

**Comment by hbonnavaud** [comment]
Found the issue.
`K.image_dim_ordering() == 'th'` in resnet.py is not available anymore. I replaced it by `K.image_data_format() == 'th'` following many comments online. However, K.image_data_format() is not just a renaming a some people said, but the output of the function also changed.

'th' is no more a possible output, and I had to replace `K.image_dim_ordering() == 'th'` by ``K.image_data_format() == 'channels_last' to make it work.
